name: Comment on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Leave a comment
        uses: Yonava/nutri-log-snhu
        with:
          message: "Good luck on the code review"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
